# Generated by Django 4.2.20 on 2025-03-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('birthDate', models.DateField()),
                ('address', models.TextField()),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('doctor', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('givenPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JasurPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('birthDate', models.DateField()),
                ('address', models.TextField()),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('doctor', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('givenPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SardorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('birthDate', models.DateField()),
                ('address', models.TextField()),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('doctor', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('givenPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoirPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('birthDate', models.DateField()),
                ('address', models.TextField()),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('doctor', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('givenPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
