# Generated by Django 4.2.20 on 2025-03-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpost',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='generalpost',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jasurpost',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jasurpost',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jasurpost',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jasurpost',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sardorpost',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sardorpost',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sardorpost',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sardorpost',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zoirpost',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zoirpost',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zoirpost',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zoirpost',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
    ]
